version: "3.2"

services:
#  nacos: # 标识服务的名称
#    image: nacos/nacos-server  # 拉取的镜像
#    environment: # 环境变量
#      MODE: standalone
#    ports: # 端口映射
#      - "8848:8848"
  mysql57:  # 等同于 --name mysql57
    image: mysql:5.7.41
    environment:
      MYSQL_ROOT_PASSWORD: 88888888
    volumes: # 挂载目录
      - "$PWD/mysql/data:/var/lib/mysql"
      - "$PWD/mysql/conf:/etc/mysql/conf.d/"

  eurekaserver : # 标识服务的名称
    build: ./eureka-server # 从当前目录下的eureka-server目录构建镜像
    ports:
      - "10086:10086"

  userservice: # 标识服务的名称
    build: ./user-service # 从当前目录下的user-service目录构建镜像

  orderservice:
    build: ./order-service # 从当前目录下的order-service目录构建镜像

  gateway:
    build: ./gateway # 从当前目录下的gateway目录构建镜像
    ports:
      - "10010:10010"

## 使用docker-compose up -d 启动所有服务