server:
  port: 10012
logging:
  level:
    cn.xxx: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  application:
    name: gateway
  cloud:
    gateway:
      websocket:
        enabled: true # 开启websocket支持
      routes:
        - id: oauth-service
          uri: lb://uaaservice
          predicates:
            - Path=/oauth/**
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址   http://localhost:8081/tUsers/1  ===》http://localhost:10012/tUsers/1
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/tUsers/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
        - id: audio # websocket路由名称
          uri: lb:ws://orderservice
          predicates:
            - Path=/ws_audio/**
              # ws://localhost:10012/ws_audio/audio  路由到 ws://localhost:8088/ws_audio/audio
          filters:
            - StripPrefix=1 # 转发时去掉第一层路径 ws://localhost:8088/audio
      default-filters: # 全局过滤器 对多有的路由都生效
        - AddRequestHeader=Truth,Itcast is freaking awesome!
      globalcors: # 全局跨域配置
        add-to-simple-url-handler-mapping: true # 解决Options请求报错
        cors-configurations:
          '[/**]':  #所有的请求都拦截
            allowedOrigins: #允许哪些网站的跨域请求
              - "http://127.0.0.1:8848"
              - "http://localhost:8848"
              - "http://www.leyou.com"
              - "http://127.0.0.1:3000"
              - "http://localhost:3000"
            allowedMethods: #允许的请求方法
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
              - "HEAD"
              - "PATCH"
            allowCredentials: true #是否允许发送Cookie
            maxAge: 360000 #跨域检测的有效期，单位为秒



eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka