server:
  port: 10010
logging:
  level:
    cn.xxx: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址   http://localhost:8081/user/2  ===》http://localhost:10010/user/2
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      default-filters: # 全局过滤器 对多有的路由都生效
        - AddRequestHeader=Truth

      globalcors: # 全局跨域配置
        add-to-simple-url-handler-mapping: true # 解决Options请求报错
        cors-configurations:
          '[/**]':  #所有的请求都拦截
            allowedOrigins: #允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods: #允许的请求方法
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
              - "HEAD"
              - "PATCH"
            allowedHeaders:
                - "*" #允许所有请求头
            allowCredentials: true #是否允许发送Cookie
            maxAge: 360000 #跨域检测的有效期，单位为秒

eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka