server:
  port: 8081

spring:
  application:
    name: userservice # userservice的服务名称
  datasource:
    url: jdbc:mysql://mysql57:3306/cloud-user?useSSL=false
    username: root
    password: 88888888
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: cn.xxx.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.xxx: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
pattern:
  name: 本地环境local